### PR TITLE
Added studio128.exr : a small hdri suitable for fast shader previews

### PR DESCRIPTION
**Pull request by danieldresser-ie**
The default hdri is high resolution, which makes it harder to sample.  For something like a quick preview render of a small shader ball, this less detailed image gives a similar result but with less noise.

### CODE REVIEW

**Comment by andrewkaufman** [comment]
Any reason we never merged this one?

**Comment by johnhaddon** [comment]
> Any reason we never merged this one?

I'm not sure I even noticed it until now, but it doesn't seem suitable to be the standard HDRI in the ShaderBalls. We need to be able to preview mirror reflections there, and it's not hi-res enough. Did you have another use in mind @danieldresser-ie ?

**Comment by danieldresser-ie** [comment]
It's maybe not pretty for previewing mirror reflections, but still seems to be enough to tell what you're doing?  At the time I was testing, fast and clean seemed more important to making shader balls useful than having high frequency content.  If you need to adjust between a roughness of 0.002 and 0.001, you probably can't judge that on a shader ball anyway.

Of course, it's all academic at the moment since Arnold doesn't support multiple universes, and no one is using shader balls.

**Comment by johnhaddon** [comment]
> If you need to adjust between a roughness of 0.002 and 0.001, you probably can't judge that on a shader ball anyway.

I tested the low res HDRI against the hi res one, and low res with roughness zero felt roughly equivalent to hi res with roughness 0.1 or more. So I don't think we're talking about minutiae in the third decimal place.

> Of course, it's all academic at the moment since Arnold doesn't support multiple universes, and no one is using shader balls.

Appleseed and 3delight do, but I'm going to close this anyway. I think this HDRI is too low res to be serviceable for tight reflections, and I haven't noticed speed being a real issue anyway. Perhaps there's a sweet spot somewhere in the middle - if so, please feel free to reopen.

**Pull request closed without merging**
